# Generated by Django 3.2.25 on 2024-08-16 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatersession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
