name: Dockerfile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "docker-compose.yml"
        test-container: web
        test-command: "python manage.py test"


