name: Simpledjango CI
# playing with notes from: https://www.hacksoft.io/blog/github-actions-in-action-setting-up-django-and-postgres
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: url_shortener_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
